# Generated by Django 4.1 on 2022-08-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('ticker', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('importance', models.CharField(max_length=100, null=True)),
                ('previous', models.CharField(max_length=100, null=True)),
                ('forecast', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('actual', models.CharField(max_length=100, null=True)),
                ('alldayevent', models.BooleanField(default=False, max_length=100, null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('revised', models.TextField(blank=True)),
                ('lastupdate', models.DateTimeField(null=True)),
            ],
        ),
    ]
